version: "3.3"  # optional since v1.27.0

services:

  db:

    image: 'postgres:12.6'
    
    ports: 
      - "5432:5432"

    volumes:
      - ./pgdata:/var/lib/postgresql/data

    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data

    networks: 
      - local_net
  
  pgAdmin:

    image: 'dpage/pgadmin4'

    environment: 
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      - PGADMIN_LISTEN_PORT=80

    ports:
      - "8080:80"

    depends_on: 
      - db

    networks: 
      - local_net

#    volumes:
#      - ./pgadmin-data/var/lib/pgadmin

  tanks:

    image: tanks

    build: ./Tank-Warehouse-Web-service

    command: python server.py

    ports:
      - "5002:5000"

    networks: 
      - local_net

#    deploy:
#        replicas: 4

    volumes:
      - ./Tank-Warehouse-Web-service:/code

  songs:

    image: songs

    build: ./Songs-service

    ports:
      - "5001:5000"

    depends_on: 
      - tanks
      - db

    networks: 
      - local_net

    volumes:
      - ./songsData:/app

volumes:
  pgadmin-data:
  pgdata:
  songsData:    

networks: 
  local_net:
