version: "3.3"

services:

  songs-image:

    ports:
    - "5000:5000"
    depends_on: 
    - db
    - pgAdmin

  db:
    image: 'postgres:12.6'
   
    ports: 
    - "5432:5432"

    volumes:
    - ./pgdata:/var/lib/postgresql/data

    environment: 
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - PGDATA=/var/lib/postgresql/data
 
  pgAdmin:

    image: 'dpage/pgadmin4'

    environment: 
    - PGADMIN_DEFAULT_EMAIL=user@domain.com
    - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    - PGADMIN_LISTEN_PORT=80

    ports:
    - "8080:80"

    links:
    - "db:pgsql-server"

    depends_on: 
    - db

    volumes:
    - ./pgadmin-data/var/lib/pgadmin

volumes:
  pgadmin-data:
  pgdata: 

